language: java
jdk:
  - oraclejdk8

addons:
  postgresql: "9.3"

env:
  - BUILD_TOOL=maven

before_script:
  - psql -c "create database catwatch;" -U postgres -h localhost
  - psql -c "create database catwatch_test;" -U postgres -h localhost
  - psql -c "create user cat1 with password 'cat1';" -U postgres -h localhost

script:
  - ./build.sh

after_success:
  - ./build-coverage.sh

notifications:
  email:
    - angela.igreja@zalando.de 
    - ruben.barilani@zalando.de 
    - roman.bobin@zalando.de 
    - manuel.kunz@zalando.de 
    - frank.schulze@zalando.de 
    - priyadarshini.maji@zalando.de 

